version: '3.1'

services:
  # mysql
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: qwe123
    image: mysql:latest
    container_name: mysql
    restart: always
    command:
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_general_ci
      --explicit_defaults_for_timestamp=true
      --lower_case_table_names=1
      --max_allowed_packet=128M
    volumes:
      - ./mysql/db:/var/lib/mysql
    ports:
      - 3306:3306

  nacos:
    container_name: nacos-server
    image: nacos/nacos-server:latest
    ports:
      - "8848:8848"
    environment:
      MODE: standalone
    restart: always

  sentinel:
    container_name: sentinel-dashboard
    image: bladex/sentinel-dashboard:latest
    ports:
      - "8858:8858"
    restart: always
